# coding: utf-8
MOVE_FORWARD = 'FORWARD'
MOVE_BACKWARD = 'BACKWARD'
MOVE_RIGHT = 'RIGHT'
MOVE_LEFT = 'LEFT'
STOP = 'STOP'
NOOP = 'NOOP'

MOVEMENTS = (MOVE_FORWARD, MOVE_BACKWARD, MOVE_RIGHT, MOVE_LEFT)
