# coding: utf-8
PORT = "5556"

REQUEST_TIMEOUT = 2500

MOVE_FORWARD = 'FORWARD'
MOVE_BACKWARD = 'BACKWARD'
MOVE_RIGHT = 'RIGHT'
MOVE_LEFT = 'LEFT'
STOP = 'STOP'

MOVEMENTS = (MOVE_FORWARD, MOVE_BACKWARD, MOVE_RIGHT, MOVE_LEFT)
